services:
  api:
    build:
      context: .
      dockerfile: src/GtMotive.Estimate.Microservice.Host/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__SqlServer: "Server=sqlserver;Database=MicroserviceDb;User Id=sa;Password=Str0ng!Passw0rd;TrustServerCertificate=True;"
    restart: on-failure
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ng!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
